name: Create a Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  check-workflows:
    uses: ./.github/workflows/check-workflows.yml

  build-artifacts:
    needs: check-workflows
    uses: ./.github/workflows/windows-build.yml
    with:
      upload-artifacts: true

  create-release:
    needs: build-artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Create a Release
      run: gh release create ${{ github.ref }} -F ReleaseNote.md

    - name: Download ocesql.exe
      uses: actions/download-artifact@v4
      with:
        name: ocesql.exe

    - name: Download ocesql4j.jar
      uses: actions/download-artifact@v4
      with:
        name: ocesql4j.jar

    - name: Publish artifacts
      run: |
        gh release upload ${{ github.ref_name }} ocesql.exe --clobber
        gh release upload ${{ github.ref_name }} ocesql4j.jar --clobber
